/**
 * Core domain types for NFL Edge Simulator 2026.
 * Shared across data loaders, simulation engine, and UI components.
 */

/** Single NFL franchise with offensive/defensive scoring rates used by the model. */
export interface Team {
  id: string;
  name: string;
  abbreviation: string;
  city: string;
  conference: "AFC" | "NFC";
  division: "East" | "North" | "South" | "West";
  /** Primary brand color (hex) for subtle UI accents */
  primaryColor: string;
  secondaryColor: string;
  /**
   * Offensive points per game (model input).
   * Higher = stronger offense. Edit in teams.json and re-run precompute.
   */
  offensePpg: number;
  /**
   * Defensive points allowed per game (model input).
   * Lower = stronger defense.
   */
  defensePapg: number;
  /**
   * Optional power-user override multiplier (1.0 = neutral).
   * Applied on top of offensePpg when present.
   */
  offenseMultiplier?: number;
  defenseMultiplier?: number;
  /** Prior-season PPG used in the blend (from ESPN standings). */
  priorOffensePpg?: number;
  priorDefensePapg?: number;
  /** Current-season YTD rates (null before any games). */
  currentOffensePpg?: number | null;
  currentDefensePapg?: number | null;
  /** Regular-season games played in the current season. */
  gamesPlayed?: number;
  /** Weight toward current season in [0, 1]. */
  blendWeight?: number;
}

/** Provenance for team ratings written by npm run fetch-stats. */
export interface TeamStatsMeta {
  source: "espn";
  priorSeason: number;
  currentSeason: number;
  /** ISO timestamp when ratings were last pulled */
  statsAsOf: string;
  /**
   * Approximate completed week inferred from max games played.
   * null = preseason / no current-season games yet.
   */
  statsWeek: number | null;
  /** Max games played by any team in the current season */
  gamesPlayedMax: number;
  /** GP at which current season reaches 100% blend weight */
  blendGamesFullWeight: number;
  /** Mean blend weight across the league (0 = all prior season) */
  blendWeightCurrentMean: number;
  leagueAvgPpg: number;
  note: string;
}

/** One regular-season game on the 2026 schedule. */
export interface Game {
  id: string;
  week: number;
  /** ISO date string YYYY-MM-DD */
  date: string;
  /** Local kickoff time display, e.g. "1:00 PM ET" */
  kickoff: string;
  awayTeamId: string;
  homeTeamId: string;
  /** Optional venue note */
  venue?: string;
  /** TV / streaming network from ESPN when available */
  broadcast?: string;
  /** ESPN event id (numeric string) */
  espnEventId?: string;
  /** ESPN matchup name, e.g. "New England Patriots at Seattle Seahawks" */
  name?: string;
}

/**
 * Pre-computed Monte Carlo prediction for a single game.
 * Generated by scripts/precompute-predictions.ts so the site stays fast.
 */
export interface GamePrediction {
  gameId: string;
  /** Mean predicted home score across simulations */
  predictedHomeScore: number;
  /** Mean predicted away score across simulations */
  predictedAwayScore: number;
  /** Home team margin of victory (negative = home underdog). Spread is from home perspective: e.g. -3.5 means home favored by 3.5 */
  predictedSpread: number;
  /** Expected combined points */
  predictedTotal: number;
  /** P(home wins) in [0, 1] */
  homeWinProb: number;
  /** P(away wins) in [0, 1] */
  awayWinProb: number;
  /** P(exact tie) before any OT simplification */
  tieProb: number;
  /** Expected scoring rates (Poisson lambdas) used for the sim */
  lambdaHome: number;
  lambdaAway: number;
  simulations: number;
  /** Sample final scores for detail-page exploration */
  sampleOutcomes: SampleOutcome[];
  /** Human-readable strength of favorite */
  interpretation: string;
  generatedAt: string;
}

export interface SampleOutcome {
  homeScore: number;
  awayScore: number;
  count: number;
  pct: number;
}

/** Fully joined game row for tables and cards. */
export interface GameWithPrediction {
  game: Game;
  prediction: GamePrediction;
  homeTeam: Team;
  awayTeam: Team;
}

export interface SeasonMeta {
  season: number;
  label: string;
  currentWeek: number;
  totalGames: number;
  simulationsPerGame: number;
  homeFieldAdvantage: number;
  leagueAvgPpg: number;
  generatedAt: string;
  disclaimer: string;
}

export interface PredictionsFile {
  meta: SeasonMeta;
  predictions: GamePrediction[];
}

export interface ScheduleFile {
  season: number;
  note: string;
  games: Game[];
}

export interface TeamsFile {
  season: number;
  note: string;
  leagueAvgPpg: number;
  /** Present after running npm run fetch-stats */
  statsMeta?: TeamStatsMeta;
  teams: Team[];
}
